### ISSUE TITLE
Removal of additional CWD to PYTHONPATH

### ISSUE THREAD

**Issue by okken** [bigsassy/pytest-pythonpath#14]
I recommend this plugin to loads of people.  
However, one thing has always bothered me.  

These few lines:
```python
# py.test has an issue where the cwd is not in the PYTHONPATH. Fix it here.
    if os.getcwd() not in sys.path:
        sys.path.insert(0, os.getcwd())
```

The pytest decision to not add cwd is [not an accident](https://docs.pytest.org/en/stable/pythonpath.html#invoking-pytest-versus-python-m-pytest).   
For projects that use a src directory, it's not a problem either way.  
But for projects that do NOT use a src directory convention, and are intending to test Python packages, setting the python path to include the current directory can [cause problems](https://hynek.me/articles/testing-packaging/). 

Granted, projects that are testing packages generally don't need this plugin.  

However, .... including the cwd can still cause confusion.  
If I install this plugin, and run the tests from the top level directory where importing my code under test is possible, everything will work fine. Then if I cd into the tests directory or a test subdirectory, then my tests don't run. I think that'd cause more confusion than the plugin fixes.  

Anyway. This is more of a question than anything else. Why'd you include CWD?  

Also, if you decide to blow this off and leave it in, I think it'd be cool to mention this behavior in the README.

Thanks.

**Comment by bigsassy** [comment]
Hey, @okken 👋 

> This is more of a question than anything else. Why'd you include CWD?

I LOVE that others have gotten so much use out of this package, but its origins were for solving a specific problem I was having with pytest 7 years ago.  In other words, I included it because I needed it.

I'm pretty sure more thought was put into this post than I put into adding those two lines of code.  My thought process was probably "Does this work?...*runs tests*...Yup, that got it!" 😅 

All this to say, you bring up an excellent point and I'm happy to update this library (or accept pull requests).  I'm happy to hear your thoughts on what those changes could look like.  Perhaps an extra config option to remove that behavior (defaulting to the current behavior) along with a README update?

**Comment by bigsassy** [comment]
I'm going to close this issue now.  @okken has released a new package [pytest-srcpaths](https://pypi.org/project/pytest-srcpaths/), which can resolve this issue for anyone who needs it 🎉

**Comment by okken** [comment]
👍
